steps:
- name: 'gcr.io/cloud-builders/kubectl'
  args: [
    'apply', 
    '-f', 'ui-service.yaml', 
    '-f', 'gps-service.yaml',
    '-f', 'api-gateway.yaml',
    '-f', 'ingress.yaml'
  ]
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'
